CREATE TABLE rides (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text not null,
    geo_json jsonb not null,
    total_distance decimal not null,
    surface_composition jsonb not null,
    ride_time bigint not null,
    start_address jsonb not null,
    end_address jsonb not null
);